# bincrafters-conventions:no-new-compiler-versions

environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install bincrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
  - bincrafters-package-tools --auto
