variables:
- group: conan-credentials

jobs:
- job: Linux
  pool:
    vmImage: "Ubuntu 16.04"
  timeoutInMinutes: 180
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
  - script: |
      pip install --upgrade pip
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
      ./.ci/run.sh
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
      CONAN_DOCKER_32_IMAGES: 1
  strategy:
    matrix:
      Gcc 4.9:
        CONAN_GCC_VERSIONS: 4.9
        CONAN_DOCKER_IMAGE: conanio/gcc49
      Gcc 5:
        CONAN_GCC_VERSIONS: 5
        CONAN_DOCKER_IMAGE: conanio/gcc5
      Gcc 6:
        CONAN_GCC_VERSIONS: 6
        CONAN_DOCKER_IMAGE: conanio/gcc6
      Gcc 7:
        CONAN_GCC_VERSIONS: 7
        CONAN_DOCKER_IMAGE: conanio/gcc7
      Gcc 8:
        CONAN_GCC_VERSIONS: 8
        CONAN_DOCKER_IMAGE: conanio/gcc8
      Clang 3.9:
        CONAN_CLANG_VERSIONS: 3.9
        CONAN_DOCKER_IMAGE: conanio/clang39
      Clang 4.0:
        CONAN_CLANG_VERSIONS: 4.0
        CONAN_DOCKER_IMAGE: conanio/clang40
      Clang 5.0:
        CONAN_CLANG_VERSIONS: 5.0
        CONAN_DOCKER_IMAGE: conanio/clang50
      Clang 6.0:
        CONAN_CLANG_VERSIONS: 6.0
        CONAN_DOCKER_IMAGE: conanio/clang60
      Clang 7.0:
        CONAN_CLANG_VERSIONS: 7.0
        CONAN_DOCKER_IMAGE: conanio/clang7
